add functions lz4 zstd  bvars  & bug fix
baidu/BaikalDB pull request #132
Opened 2020-12-17 09:07 UTC by wy1433

**New Features:**
- add db qps bvars by users
- noskip for auto inc field
- add last_insert_id, sign and set set MAX_LOG_LEN to 20480 for _print_query_time log
- add gflags to reduce read amplification
- add lz4 zstd compression support for rocksdb
- add funcs: date_add, date_sub, utc_timestamp, last_insert_id
- set filed charset default utf8 adapts for dotnet mysql.client

**Bug Fixes:**
- prepare insert current time default value
- fix count(*) return NULL expected 0 when filter expr is always false
- ignore non-json format comment for sql string
- update last_insert_id when client set the value

2020-12-17 12:20 UTC, lgqss requested changes

2020-12-17 12:20 UTC, lgqss commented on src/physical_plan/auto_inc.cpp
> +    if (field_info !=nullptr && boost::algorithm::icontains(field_info->comment, "noskip")) {
init field时加个判断flag

2020-12-17 12:20 UTC, lgqss commented on src/protocol/state_machine.cpp
> +		            out[0],
缩进

2020-12-17 12:20 UTC, lgqss commented on src/protocol/state_machine.cpp
> +    }
ignore_reg时干啥的

2020-12-17 12:20 UTC, lgqss commented on src/physical_plan/auto_inc.cpp
> +    // 通过字段注释可以标示:自增id不会随着插入id进行跳号,当插入的自增id来自于异构数据源时,用于避免自增id的双写冲突问题.
这样做，不会造成id覆盖吗

2020-12-17 13:37 UTC, wy1433 commented on src/protocol/state_machine.cpp
> +    }
部分mysql client 会在sql的中间添加 类似 insert into t /* comment */ values() 如果不去掉，后续parser会出错

2020-12-17 13:43 UTC, wy1433 commented on src/physical_plan/auto_inc.cpp
> +    // 通过字段注释可以标示:自增id不会随着插入id进行跳号,当插入的自增id来自于异构数据源时,用于避免自增id的双写冲突问题.
与异构数据源（例如mysql）双向同步自增id做主键时， auto_inc的默认行为都是更新为当前最大值假设max_id，这样两个DB的新增记录将同时从max_id + 1开始编号，造成双写冲突。

2020-12-17 14:02 UTC, wy1433 commented on include/engine/transaction.h
> +//typedef std::shared_ptr<Transaction> SmartTransaction;
已还原

2020-12-18 02:30 UTC, lgqss commented on src/protocol/state_machine.cpp
> +    }
ignore_reg但是这个变量没用到

2020-12-18 06:40 UTC, lgqss approved these changes

2020-12-18 06:40 UTC, merged