make cstore vectorization when  table_seek
baidu/BaikalDB pull request #141
Opened 2021-03-19 09:33 UTC by wy1433

提升列存主键扫描速度
1. 列存扫表get_next_columns改为:get_column，一次扫描多列，改为一次扫描一列，提高cpu cache局部性
2. 先扫描带过滤条件的列，然后过滤，当查询条件过滤率高时，可以减少普通列扫描次数

2021-03-22 04:37 UTC, lgqss requested changes

2021-03-22 04:37 UTC, lgqss commented on src/exec/rocksdb_scan_node.cpp
> +            if (filter.get()) {
filter != nullptr

2021-03-22 04:37 UTC, lgqss commented on src/exec/rocksdb_scan_node.cpp
> +                if (_limit != -1 && _num_rows_returned + num >= _limit) break;
加大括号

2021-03-22 06:56 UTC, wy1433 commented on src/engine/table_iterator.cpp
> +                } else {
当列的值为空或默认值时，列存并不会存这个key，value，因此主键列的key个数 >= 普通列。
例如：

2021-03-22 07:09 UTC, wy1433 commented on src/exec/rocksdb_scan_node.cpp
> +
index_condition_pushdown调用need_pushdown， need_pushdown需要判断_use_get，在上面时 _use_get尚未得到正确赋值。

2021-03-22 08:24 UTC, lgqss commented on src/engine/table_iterator.cpp
> +                } else {
我是说else分支

2021-03-23 03:13 UTC, wy1433 commented on src/engine/table_iterator.cpp
> +                } else {
当0 < filter_num < 63时， 主键列因被过滤而往下走，普通列没有走seek，需要通过next去匹配主键。

2021-03-23 03:29 UTC, wy1433 commented on src/engine/table_iterator.cpp
> +        if (filter_num > 63) {
这块主要参考https://github.com/facebook/rocksdb/wiki/Iterator-Implementation
与少量的测试给出了63的经验值，大概估算过程是：Seek的主要过程需用到TwoLevelIterator，需要2个过程IndexBlock与DataBlock，DataBlock的默认大小64k，按照二分查找，大概需要16次，由于扫描可能用到L0到L6的多个TwoLevelIterator，取评估值为4次，因此粗略估计认为一次seek相当于16*4=64次next操作，整个过程仅是一个大概估算，在实测中过滤率高于过滤低的情况下性能均有所提升，但不一定是最优值。

2021-03-23 03:31 UTC, wy1433 commented on src/engine/table_iterator.cpp
> +        if (filter_num > 63) {
这块主要参考https://github.com/facebook/rocksdb/wiki/Iterator-Implementation
与少量的测试给出了63的经验值，大概估算过程是：Seek的主要过程需用到TwoLevelIterator，需要2个过程IndexBlock与DataBlock，DataBlock的默认大小64k，按照二分查找，大概需要16次，由于扫描可能用到L0到L6的多个TwoLevelIterator，取评估值为4次，因此粗略估计认为一次seek相当于16*4=64次next操作，整个过程仅是一个大概估算，在实测中过滤率高于过滤低的情况下性能均有所提升，但不一定是最优值。

2021-03-23 06:00 UTC, wy1433 commented on src/engine/table_iterator.cpp
> +            if (!column_key.starts_with(prefix_key.data())){
直接比较完整的key，需要每次比较都更新primary_key的编码里field_id的部分，分成两部分的话prefix_key同一列都是相当的，field_id的计算部分可以放在循环外面。

2021-03-23 06:55 UTC, lgqss approved these changes

2021-03-23 06:56 UTC, merged