support binlog meta table ttl; support operator _binary;  add func last_insert_id(expr); add flag for ignore case for schema info; optimize load balance
baidu/BaikalDB pull request #158
Opened 2021-07-09 03:27 UTC by wy1433

- binlog元数据表支持ttl
- 兼容.netcore对string与binary的处理差异，支持_binary EXPR用法及blob类型返回
-  增加工具update_num_table_lines，用于修正region的num_table_lines，用法：./update_num_table_lines -region_id=$(id) -num_table_lines=$(lines)
- 增加函数last_insert_id(expr)，可以在session级别保存表达式执行结果
- 支持库名，表名，别名，大小写不敏感用法，schema_ignore_case=true开启
- 支持多表查询时，不同表字段相同，查询时没有指定表名的歧义消除功能，disambiguate_select_name=true开启
- peer_load_balance增加balance_add_peer_num参数，默认每张表迁移10个，可不重启meta动态修改以调整迁移速度
- leader_load_balance放宽transfer leader的候选peer的选择限制
- 修复了一些cstore， binlog， prepare相关的bug

2021-07-09 06:22 UTC, lgqss requested changes

2021-07-09 06:22 UTC, lgqss commented on src/meta_server/region_manager.cpp
> +DECLARE_int32(balance_add_peer_num);
在这里DEFINE就行

2021-07-09 06:22 UTC, lgqss commented on src/protocol/network_server.cpp
> +                    DB_NOTICE_LONG("date_hour_min=[%04d-%02d-%02d\t%02d\t%02d] sum_pv_avg_affected_scan_filter_err="
可以把SQL_TRACE长度设长

2021-07-09 06:22 UTC, lgqss commented on src/tools/update_num_table_lines.cpp
> +int update_num_table_lines(int64_t region_id, int64_t num_table_lines) {
直接做个接口改呢？

2021-07-09 06:22 UTC, lgqss commented on proto/store.interface.proto
> +    optional int64 last_insert_id = 22;
为啥这个需要store处理？

2021-07-09 06:46 UTC, wy1433 commented on proto/store.interface.proto
> +    optional int64 last_insert_id = 22;
这是last_insert_id(expr)带参数版本的用法，目的是更新字段的同事把更新值返回给客户端的AUTO_INCREMENT column。
参见：http://www.sqlines.com/mysql/how-to/select-update-single-statement-race-condition

2021-07-09 09:52 UTC, wy1433 commented on src/tools/update_num_table_lines.cpp
> +int update_num_table_lines(int64_t region_id, int64_t num_table_lines) {
下次改成接口

2021-07-15 03:51 UTC, lgqss requested changes

2021-07-15 03:51 UTC, lgqss commented on src/exec/dml_node.cpp
> +            state->last_insert_id = expr->get_value(row).cast_to(slot.slot_type()).get_numberic<int64_t>();
看着和mysql语义不符

2021-07-15 08:10 UTC, wy1433 commented on src/exec/dml_node.cpp
> +            state->last_insert_id = expr->get_value(row).cast_to(slot.slot_type()).get_numberic<int64_t>();
已修改

2021-07-15 11:18 UTC, lgqss approved these changes

2021-07-15 11:19 UTC, merged