comb multi in predicate
baidu/BaikalDB pull request #160
Opened 2021-08-27 11:58 UTC by wy1433

**允许多个in组合条件命中索引**
例如索引： key idx_abcd(`a`, `b`, `c`, `d`), 条件：a in ("a1", "a2") and (b , c) in (("b1", "c1"), ("b2","c2"))， 会匹配索引a,b,c三个字段
条件a全匹配被裁剪，条件(b, c)全部字段匹配索引索引被裁剪，裁剪后的条件会被组合展开为索引的ranges：
```
a1, b1, c1
a2, b1, c1
a1, b2, c2
a2, b2, c2
```
若一个字段对应多个in表达式，则只会使用一个，例如：(a , b) in (("a1", "b1"), ("a2","b2")) and (b , c) in (("b1", "c1"), ("b2","c2"), ("b3","c3"))， b字段同时对应了2个in条件，则b字段只会使用in的值较少的一个，本例为会使用(a,b)
 (a,b)全部字段匹配索引将会被裁剪掉，(b, c)只会索引匹配字段c，条件会被保留，但记录("b3", "c3")将会被裁剪掉。索引的ranges将被展开为：
```
a1, b1, c1
a2, b2, c1
a1, b1, c2
a2, b2, c2
```
相关测试用例，可以用explain format='plan' select ... 进行分析：
```
CREATE TABLE `testin` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `a` varchar(1024) NOT NULL ,
  `b` varchar(1024) NOT NULL ,
  `c` varchar(1024) NOT NULL ,
  `d` varchar(1024) NOT NULL ,
  `e` varchar(1024) NOT NULL ,
  `f` varchar(1024) NOT NULL ,
  PRIMARY KEY (`id`),
  KEY idx_abcdef(`a`,`b`,`c`,`d`,`e`,`f`)
);
system sleep 30;

INSERT INTO testin VALUES(NULL, "a1", "b1", "c1", "d1", "e1", "f1");
INSERT INTO testin VALUES(NULL, "a2", "b2", "c2", "d2", "e2", "f2");
INSERT INTO testin VALUES(NULL, "a3", "b3", "c3", "d3", "e3", "f3");
INSERT INTO testin VALUES(NULL, "a4", "b4", "c4", "d4", "e4", "f4");
INSERT INTO testin VALUES(NULL, "a5", "b5", "c5", "d5", "e5", "f5");
INSERT INTO testin VALUES(NULL, "a6", "b6", "c6", "d6", "e6", "f6");

# 单in组合
select id from testin where a IN ("a1" , "a2") and b IN ("b1", "b2", "b3");
select id from testin where a IN ("a1" , "a2") and b IN ("b1", "b2", "b3")  and c IN ("c1", "c2") ;

# 单in与row_expr组合
select id from testin where  a in ("a1", "a2") and (b , c) in (("b1", "c1"), ("b2","c2"));

# row_expr组合
select id from testin where  (a , b) in (("a1", "b1"), ("a2","b2")) and (c , d) in (("c1", "d1"), ("c3","d3"));

# 字段有重叠
select id from testin where  a in ("a1", "a2") and (a , b) in (("a1", "b1"), ("a3","b3"));
select id from testin where  (a, b) IN (("a1", "b1")) and (b, c) IN (("b1","c1"));
select id from testin where  (a, b) IN (("a1", "b1")) and (b, c) IN (("b1","c2"));
select id from testin where  (a , b) in (("a1", "b1"), ("a2","b2")) and (b , c) in (("b1", "c1"), ("b2","c2"));
select id from testin where  (a , b) in (("a1", "b1"), ("a2","b2")) and (b , c) in (("b2", "c1"), ("b1","c2"));
select id from testin where  (a , b) in (("a1", "b1"), ("a2","b2")) and (b , c) in (("b1", "c1"), ("b2","c2"), ("b3","c3"));

select id from testin where (a , b) in (("a1", "b1"), ("a2","b1")) and (b , c) in (("b1", "c1"), ("b2","c2"), ("b3","c3"));
select id from testin where  (a, b) in ( ("a1","b1"),("a2","b1"),("a3","b2"),("a4","b2") ) and (b, c) in ( ("b1","c1"),("b1","c2"),("b2","c3"),("b2","c4"));
select id from testin where  a in ("a1", "a2", "a3") and (a , b) in (("a1", "b1"), ("a2","b2")) and (a, c) in (("a1", "c1"), ("a3","c3"))

# 多in组合与range组合
select id from testin where (a , b) in (("a1", "b1"), ("a2","b2")) and (b , c) in (("b1", "c1"), ("b2","c2"), ("b3","c3")) and d in ("d1","d2","d3","d4") and e > "e1" and e < "e4";

# Row Expr EQ
select id from testin where (a , b) = ("a1", "b1") and (b, a) = ("b1", "a2");
select id from testin where (a,b) = ("a1","b1") and (b,a) = ("b1","a1");
select id from testin where a = "a1" and b="b1" and (a , b) = ("a1", "b1");
select id from testin where a = "a1"  and (a , b) = ("a1", "b1");

# EQ IN Range组合
select id from testin where   a ="a1" and b in ("b1", "b2") and (b,c) in (("b1","c1"),("b2","c2")) and a < "a5" and (d, e) >= ("d1","e1");
```

2021-08-30 09:09 UTC, lgqss reviewed
考虑：(a , b) in (("a1", "b1"), ("a2","b1")) and (b , c) in (("b1", "c1"), ("b2","c2"), ("b3","c3"))

a,b 是 a1,b1,  a2,b1,  a3,b2,  a4,b2；b,c 是b1,c1,  b1,c2,  b2,c3,  b2,c4

2021-08-31 10:15 UTC, wy1433 commented on src/physical_plan/index_selector.cpp
> +            }
1个字段对应多个in preds时 例如: a in ("a1", "a2") and (a, b) in (("a1","b1")),取数量少的pred

2021-08-31 10:16 UTC, wy1433 commented on src/exec/filter_node.cpp
> +                        preds.slot_ref->tuple_id(), preds.slot_ref->slot_id());
字段b对应两个in preds，一个是(a, b), 一个是（b,c）的话，b的idx分别为1与0， 存slot_ref可以多个in preds用一个

2021-09-03 14:04 UTC, lgqss requested changes

2021-09-06 03:56 UTC, wy1433 commented on src/exec/access_path.cpp
> +            case LIKE:
https://github.com/baidu/BaikalDB/blob/master/src/physical_plan/index_selector.cpp#L442

2021-09-06 06:35 UTC, wy1433 commented on src/exec/access_path.cpp
> +                        in_row_expr_map[*range.conditions.begin()] = std::pair<uint32_t, uint32_t>(in_records.size(), 1);
in_row_expr 组合展开时，后续字段需要与首字段对齐，在in_records展开为comb_in_records时，因为当前字段写在for循环的外层，所以当前字段的eq_in_values的每个值都需要连续赋值in_records.size()个后，再会计算下一个，这里把连续赋值的次数定义为步长offset，步长offset具有稳定性，不管组合展开了多少倍，in_row_expr的后续字段只需要也重复赋值offset次即可对齐。

> **举例：**
```
索引：idx_abcde
条件：a in ("a1", "a2") and (b, d) in  (("b1","d1"),("b2","d2")) and c in ("c1","c2","c3") 
0:初始化: in_records.size() = 1

1: 展开a， offset = 1
a1
a2

2：展开b, offset  = 2， b in（"b1", "b2"）的每个值重复赋值次数为in_records.size() = 2
a1 b1
a2 b1
a1 b2
a2 b2

3: 展开c， offset = 4， 注意此时c的值（c1, c2, c3）的重复次数=offset =4， b的重复次数依旧=2， a的重复次数依旧=1
a1 b1 c1
a2 b1 c1
a1 b2 c1
a2 b2 c2
a1 b1 c2
a2 b1 c2
a1 b2 c2
a2 b2 c2
a1 b1 c3
a2 b1 c3
a1 b2 c3
a2 b2 c3

4： 处理d，d in (d1, d2) 因为d属于 in_row_expr的非首字段，不对数组in_records进行展开，需要按照b的offset=2进行填充。相当于对于d1，需要连续赋值offset次（本例为2次，再赋值b2），依次循环既可以一一对齐。
a1 b1 c1 d1
a2 b1 c1 d1 // d offset = 2
a1 b2 c1 d2
a2 b2 c2 d2 // d offset = 2
a1 b1 c2 d1
a2 b1 c2 d1
a1 b2 c2 d2
a2 b2 c2 d2
a1 b1 c3 d1
a2 b1 c3 d1
a1 b2 c3 d2
a2 b2 c3 d2

```

2021-09-06 06:40 UTC, lgqss commented on src/exec/access_path.cpp
> +            case LIKE:
like匹配fulltext的，不会进入这里

2021-09-06 07:21 UTC, merged