兼容性提升
baidu/BaikalDB pull request #171
Opened 2022-01-04 08:53 UTC by wy1433

- 新增函数： timestamp, lpad, rpad, time_format, convert_tz, isnull, database, cast, convert, default
- 新增系统表：ROUTINES，KEY_COLUMN_USAGE ， REFERENTIAL_CONSTRAINTS
- 兼容jdbc8.0驱动
- 支持表注释，并支持alter table修改表注释，及comment里面内容
- drop index忽略索引名称大小写
- 支持sql单行注释写法
- 一些bug fix

2022-01-05 11:58 UTC, lgqss requested changes

2022-01-05 11:58 UTC, lgqss commented on include/sqlparser/sql_lex.l
> +"--".* {/* single line comment; do nothing */}
--后面加个空格
应该是[^\n]*?

2022-01-05 11:58 UTC, lgqss commented on include/sqlparser/sql_parse.y
> +	    FuncExpr* fun = new_node(FuncExpr);
缩进
下同

2022-01-05 11:58 UTC, lgqss commented on include/sqlparser/sql_parse.y
> +FunctionNameCurTimestamp:
测了下，now必须带()

2022-01-05 11:58 UTC, lgqss commented on include/sqlparser/sql_parse.y
> +        assign->key = "";
不需要key吗

2022-01-05 11:58 UTC, lgqss commented on src/common/common.cpp
> +        { pb::NULL_TYPE,    FieldDescriptorProto::TYPE_BOOL}
null为啥要改成bool

2022-01-05 11:58 UTC, lgqss commented on src/common/tuple_record.cpp
> +            ExprValue default_value = iter->second->default_expr_value;
这块可以去掉，已经修复成加列时候的时间
src/common/schema_factory.cpp#L491

2022-01-05 11:58 UTC, lgqss commented on src/common/tuple_record.cpp
> +        ExprValue default_value = iter->second->default_expr_value;
同上

2022-01-05 11:58 UTC, lgqss commented on src/exec/joiner.cpp
> +        if (scan_node->engine() == pb::INFORMATION_SCHEMA) {
这个是修复普通表join了INFORMATION_SCHEMA的表？

2022-01-05 11:58 UTC, lgqss commented on src/logical_plan/ddl_planner.cpp
> +    table.set_if_exist(stmt->if_exist);
直接db这边判断呢，还是说考虑并发？

2022-01-05 11:58 UTC, lgqss commented on src/logical_plan/ddl_planner.cpp
> +                    alter_request.set_op_type(pb::OP_UPDATE_TABLE_COMMENT);
这块是需要修改通用注释是吧？
那么后面的参数可以不用支持改

2022-01-06 06:01 UTC, wy1433 commented on src/exec/joiner.cpp
> +        if (scan_node->engine() == pb::INFORMATION_SCHEMA) {
修复了INFORMATION_SCHEMA的2张表join出core的问题

2022-01-06 06:02 UTC, wy1433 commented on include/sqlparser/sql_lex.l
> +"--".* {/* single line comment; do nothing */}
flex语法 . 不匹配 \n

2022-01-06 07:00 UTC, wy1433 commented on src/common/common.cpp
> +        { pb::NULL_TYPE,    FieldDescriptorProto::TYPE_BOOL}
pb没有NULL类型，用bool兼容

2022-01-06 07:02 UTC, wy1433 commented on src/logical_plan/ddl_planner.cpp
> +    table.set_if_exist(stmt->if_exist);
check_table_exist函数时在meta实现的，放在meta更简单一点

2022-01-06 08:30 UTC, wy1433 commented on src/logical_plan/ddl_planner.cpp
> +                    alter_request.set_op_type(pb::OP_UPDATE_TABLE_COMMENT);
已删除

2022-01-06 13:40 UTC, lgqss requested changes

2022-01-06 13:40 UTC, lgqss commented on src/common/datetime.cpp
> +        i ++;
i++不用空格

2022-01-06 13:40 UTC, lgqss commented on src/common/datetime.cpp
> +        i ++;
i++不用空格

2022-01-07 06:06 UTC, merged