索引优化
baidu/BaikalDB pull request #203
Opened 2022-12-09 08:44 UTC by wy1433

### 全局索引先limit后回表优化

- 背景：针对分页查询的需求， SQL类似于 select ... order by id limit 10000, 10 ，这种一般是用户翻到了第1001页，每页展示10条，为了找到这10条数据，即使limit可以下推，也需先要找到id最小的10010条，然后再取最后10条数据， 此时扫描的数据量= 10010； 此时如果业务侧能知道第10000条数据id，例如ID(10000) = 10000，则查询可以改写为：select ... where id > 10000 order by id limit 10，此时需要用户存储第1000页的最大id， 这增加了用户写sql的复杂度，更重要的时，有的场景是用户直接跳转到底1001页，业务侧也不知道上一页的最大id，针对分页场景，进行了limit的回表优化。
- 实现：
    - 首先对用户查询条件创建索引，由于索引返回的数据只包含索引字段与主键字段，扫描与返回的数据量均远小于主表，所以在索引环节完成limit的下推与过滤
    - 通过索引进行回表阶段，已完成limit，此时回表的数据量由原来的10010条减少到10条，从而大大提升了分页场景的优化速度

### 索引选择和索引range生成拆分，减少生成range开销
- 背景：查询过滤条件复杂的sql，例如 in （v1 ... v1000），生成索引的同时会生成range信息（即索引的扫描区间），对于索引较多表，一般不止一种可用的查询计划，如果全部都生成range信息，会造成额外的overhead
- 实现：虽然查询计划有多种，但经过索引选择后，最终只会有一个查询计划胜出，该优化把range信息生成延迟到索引选择之后再生成，从而避免了多索引的range生成overhead

2022-12-12 08:43 UTC, lgqss requested changes

2022-12-12 08:43 UTC, lgqss commented on src/exec/select_manager_node.cpp
> +            parent = nullptr;
为啥要判断SORT_NODE
！SORT_NODE  break，下面的LimitNode* limit = static_cast<LimitNode*>(parent);可能不是limit

2022-12-12 08:43 UTC, lgqss commented on src/exec/select_manager_node.cpp
> +int SelectManagerNode::construct_primary_possible_index_use_limit(
和construct_primary_possible_index差别不大，能复用吗

2022-12-12 08:43 UTC, lgqss commented on src/exec/scan_node.cpp
> +        if (!outer_path->need_filter() && inner_path->is_sort_index <= outer_path->is_sort_index) {
这个用处是？

2022-12-19 03:38 UTC, yz-cyz commented on src/physical_plan/index_selector.cpp
> +        // TODO: 当外层为UPDATE或DELETE时，计算covering_index可能错误
ctx不赋值，不会走到新的逻辑里，join时的逻辑和之前一样，保持不变。

2022-12-19 07:57 UTC, yz-cyz commented on src/exec/select_manager_node.cpp
> +            parent = nullptr;
不是limit_node的话，parent会是nullptr， 会走原有逻辑。 当时加个SORT_NODE的判断，是因为有时候只取limit_node会有bug， 当时优化的SQL是有SORT_NODE的，所以就加了个判断，只优化带SORT_NODE的。

2022-12-19 07:57 UTC, yz-cyz commented on src/exec/select_manager_node.cpp
> +int SelectManagerNode::construct_primary_possible_index_use_limit(
理论上可以服用， 但为了不影响原有逻辑，就单提了个函数。 后面可以考虑再合并成一个函数

2022-12-19 08:35 UTC, yz-cyz commented on include/exec/scan_node.h
> +        if (!_main_path.path(_select_idx)->index_info_ptr->is_global && _select_idx != _table_id) {
执行完索引选择后，_select_idx就不会是-1了。这个条件可以去掉， 此函数执行时在_select_idx赋值之后执行的。

2022-12-23 12:02 UTC, merged

2022-12-27 03:46 UTC, lgqss commented on src/exec/select_manager_node.cpp
> +    auto mem_row_compare = std::make_shared<MemRowCompare>(_slot_order_exprs, _is_asc, _is_null_first);
多余的？

2022-12-27 03:48 UTC, lgqss commented on src/exec/select_manager_node.cpp
> +    auto tsorter = std::make_shared<Sorter>(_mem_row_compare.get());
为啥需要个额外tsorter

2022-12-27 04:22 UTC, yz-cyz commented on src/exec/select_manager_node.cpp
> +    auto tsorter = std::make_shared<Sorter>(_mem_row_compare.get());
为什么不影响_sorter的逻辑， 这个tsorter只用来对从全局索引拿到的结果进行排序取limit用。
之前尝试用过_sorter，但_sorter的执行需要提到construct_primary_possible_index中执行。 和现有逻辑不一样， 于是就增加了个tsorter在这里执行。