Cmake gcc12
baidu/BaikalDB pull request #211
Opened 2023-02-02 17:16 UTC by codeoos

braft,brpc:fix compile error:
https://github.com/apache/brpc/pull/1783/files

2023-02-06 07:53 UTC, lgqss requested changes

2023-02-06 07:53 UTC, lgqss commented on CMakeLists.txt
> +set(CMAKE_C_COMPILER /usr/bin/gcc-12)
旧版本操作系统没有g++12，最好按照操作系统来定义

2023-02-06 07:53 UTC, lgqss commented on CMakeLists.txt
> +SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 ${DEBUG_SYMBOL} -O2 -pipe -m64 -Wall -W -fPIC -Wno-unused-parameter -Wno-strict-aliasing -Wno-parentheses -frtti -fno-omit-frame-pointer")
用c++17，兼容旧版gcc

2023-02-06 07:53 UTC, lgqss commented on cmake/rocksdb.cmake
> +        -DUSE_RTTI=ON
没必要打开RTTI

2023-02-08 10:26 UTC, codeoos commented on cmake/rocksdb.cmake
> +        -DUSE_RTTI=ON
针对关闭rtti进行编译的尝试：
docker Ubuntu18.04下使用支持c++17的编译器gcc7进行测试
protobuf =>3.18.0
brpc =>1.3.0（升级protobuf至3.12以上要升级brpc）
rocksdb =>7.7.3

在CMAKE_BUILD_TYPE=Release下
报错：
```
[ 98%] Linking CXX executable output/bin/baikaldb
libcommon.a(store.cpp.o): In function `baikaldb::Store::start_db_statistics()':
store.cpp:(.text+0xc223): undefined reference to `rocksdb::Status::Status(rocksdb::Status::Code, rocksdb::Status::SubCode, rocksdb::Slice const&, rocksdb::Slice const&)'
libcommon.a(store.cpp.o): In function `rocksdb::Statistics::Reset()':
store.cpp:(.text._ZN7rocksdb10Statistics5ResetEv[_ZN7rocksdb10Statistics5ResetEv]+0x51): undefined reference to `rocksdb::Status::Status(rocksdb::Status::Code, rocksdb::Status::SubCode, rocksdb::Slice const&, rocksdb::Slice const&)'
libcommon.a(region.cpp.o): In function `baikaldb::Region::adjustkey_and_add_version(baikaldb::pb::StoreReq const&, braft::Closure*, long, long)':
region.cpp:(.text+0x2d040): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(region.cpp.o): In function `baikaldb::Region::validate_and_add_version(baikaldb::pb::StoreReq const&, braft::Closure*, long, long)':
region.cpp:(.text+0x2d797): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(region.cpp.o): In function `baikaldb::Region::add_version_for_split_region(baikaldb::pb::StoreReq const&, braft::Closure*, long, long)':
region.cpp:(.text+0x2e28d): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(region_binlog.cpp.o): In function `baikaldb::Region::write_binlog_record(std::shared_ptr<baikaldb::TableRecord>)':
region_binlog.cpp:(.text+0xa10e): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(rocks_wrapper.cpp.o): In function `baikaldb::RocksWrapper::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
rocks_wrapper.cpp:(.text+0x3e09): undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>, bool, rocksdb::CacheMetadataChargePolicy)'
rocks_wrapper.cpp:(.text+0x4a26): undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>, bool, rocksdb::CacheMetadataChargePolicy)'
libcommon.a(rocks_wrapper.cpp.o): In function `baikaldb::RocksWrapper::remove_range(rocksdb::WriteOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::Slice const&, bool)':
rocks_wrapper.cpp:(.text+0x58d8): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(transaction.cpp.o): In function `baikaldb::Transaction::commit()':
transaction.cpp:(.text+0x2116): undefined reference to `rocksdb::Status::Status(rocksdb::Status::Code, rocksdb::Status::SubCode, rocksdb::Slice const&, rocksdb::Slice const&)'
libcommon.a(meta_writer.cpp.o): In function `baikaldb::MetaWriter::init_meta_info(baikaldb::pb::RegionInfo const&)':
meta_writer.cpp:(.text+0x73e7): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(meta_writer.cpp.o): In function `baikaldb::MetaWriter::write_meta_begin_index(long, long, long, unsigned long)':
meta_writer.cpp:(.text+0x783e): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(meta_writer.cpp.o): In function `baikaldb::MetaWriter::write_meta_after_commit(long, long, long, long, unsigned long, bool)':
meta_writer.cpp:(.text+0x7b26): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(meta_writer.cpp.o): In function `baikaldb::MetaWriter::clear_error_pre_commit(long, unsigned long)':
meta_writer.cpp:(.text+0x7f32): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(meta_writer.cpp.o): In function `baikaldb::MetaWriter::clear_meta_info(long)':
meta_writer.cpp:(.text+0x80fc): undefined reference to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)'
libcommon.a(meta_writer.cpp.o):meta_writer.cpp:(.text+0x858c): more undefined references to `rocksdb::WriteBatch::WriteBatch(unsigned long, unsigned long)' follow
```
正在找哪些地方调用了旧版本rocksdb上述函数（O2优化后实际调用的位置与编译器报错不太相符）
如果以Debug模式进行编译，报错
```
libcommon.a(rocks_wrapper.cpp.o):(.data.rel.ro._ZTIN7rocksdb16CompactionFilterE[_ZTIN7rocksdb16CompactionFilterE]+0x10): undefined reference to `typeinfo for rocksdb::Customizable'
libcommon.a(rocks_wrapper.cpp.o):(.data.rel.ro._ZTIN7rocksdb13EventListenerE[_ZTIN7rocksdb13EventListenerE]+0x10): undefined reference to `typeinfo for rocksdb::Customizable'
```
针对以上错误，修改中
不知是否方便告知内部rocksdb升级改动了哪些地方进行适配呢？

2023-02-09 13:08 UTC, lgqss commented on cmake/rocksdb.cmake
> +        -DUSE_RTTI=ON
内部没有改rocksdb的代码，这块依赖看着挺奇怪，按理说baikaldb不依赖store.cpp

2023-02-09 13:15 UTC, lgqss commented on cmake/rocksdb.cmake
> +        -DUSE_RTTI=ON
是不是缓存了一些编译结果导致的，可以改下cache-key清理掉缓存试试

2023-02-09 14:17 UTC, codeoos commented on cmake/rocksdb.cmake
> +        -DUSE_RTTI=ON
> 内部没有改rocksdb的代码，这块依赖看着挺奇怪，按理说baikaldb不依赖store.cpp

分别单独构建baikalstore和baikalmeta也是一样的，看上去应该是db,meta和store依赖了common,然后common对rocksdb有依赖？
删掉整个cmake文件夹下内容好多次了，应该不是缓存问题。编译通过的最新rocksdb版本是6.20.3

```
libcommon.a(rocks_wrapper.cpp.o):(.data.rel.ro._ZTIN7rocksdb16CompactionFilterE[_ZTIN7rocksdb16CompactionFilterE]+0x10): undefined reference to `typeinfo for rocksdb::Customizable'
libcommon.a(rocks_wrapper.cpp.o):(.data.rel.ro._ZTIN7rocksdb13EventListenerE[_ZTIN7rocksdb13EventListenerE]+0x10): undefined reference to `typeinfo for rocksdb::Customizable'
```
这个报错也没出现过么？

我用bazel试一下，看下如何

2023-03-23 13:17 UTC, lgqss commented
https://github.com/baidu/BaikalDB/pull/216

2023-03-23 13:17 UTC, closed without merging