功能完善
baidu/BaikalDB pull request #237
Opened 2024-04-16 03:00 UTC by wy1433

2024-04-16 08:34 UTC, lgqss requested changes

2024-04-16 08:34 UTC, lgqss commented on src/physical_plan/separate.cpp
> +    if (!need_separate_plan(ctx, main_table_id) && limit_node == nullptr) {
看下这个逻辑放到execute_global_flow吧，和更新主键一样，这样逻辑统一

2024-04-16 10:23 UTC, wy1433 commented on src/exec/packet_node.cpp
> +            _fields[i].length = 255;
不会，有客户端需要取length值，这里仅为了兼容

2024-04-16 11:07 UTC, wy1433 commented on src/exec/filter_node.cpp
> +        // }
mysql行为比较奇怪，无法完全兼容

2024-04-17 02:56 UTC, lgqss requested changes

2024-04-17 02:56 UTC, lgqss commented on src/protocol/network_server.cpp
> +            if (!sock->user_info || !sock->query_ctx) {
多线程冲突

2024-04-17 05:58 UTC, merged