feat: min/max消除, top n
baidu/BaikalDB pull request #249
Opened 2024-11-20 01:17 UTC by cyz-2023

* 当select字段只包括min或max函数时，转换为order by xx limit 1。
* sort算子存在limit时，使用topn
* agg/distinct没有聚合函数时，支持limit
* db支持动态修改user quota。
* 无结果时，agg返回0值
* json类型和bit类型支持
* like前缀匹配转range
* 支持distinct count(*)
* float & double返回值精度同to_string函数

2024-11-27 12:31 UTC, lgqss requested changes

2024-11-27 12:31 UTC, lgqss commented on src/expr/internal_functions.cpp
> +ExprValue json_extract1(const std::vector<ExprValue>& input) {
为啥不能调用json_extract

2024-11-27 12:31 UTC, lgqss commented on src/exec/agg_node.cpp
> +        if (packet != nullptr || _is_merger) {
啥sql

2024-11-27 12:31 UTC, lgqss commented on src/exec/fetcher_store.cpp
> +            write_binlog_param.fetcher_store = this;
啥情况会core来着

2024-11-27 12:31 UTC, lgqss commented on src/protocol/network_server.cpp
> +    old_status = SchemaFactory::get_instance()->get_instance_status(addr).status;
会传过来，为啥再拿一遍

2024-11-28 01:48 UTC, cyz-2023 commented on src/logical_plan/select_planner.cpp
> +    if (_select_exprs.size() != 1 || _select_exprs[0].nodes(0).node_type() != pb::AGG_EXPR) {
这种不可以， 就简单支持了下只有一个max或min的情况

2024-11-28 02:06 UTC, cyz-2023 commented on src/exec/sort_node.cpp
> +        _sorter = std::make_shared<TopNSorter>(_mem_row_compare.get(), _limit);
不需要所有的数据全部排序， 如果limit和总数差距较大， topn快很多。20w limit1大概快了30% - 40%

2024-11-28 02:11 UTC, cyz-2023 commented on src/runtime/topn_sorter.cpp
> +                    _mem_row_heap[0] = TopNHeapItem{std::move(row), _current_idx};
这个是为了修复一个问题。  用了topn后， 排序结果不是稳定的， 和扫描的顺序可能不一致。 为了报错原来的顺序做的。 不稳定就会有个问题。  limit 10 offset 10和limit 10 offset 15结果一样。

2024-11-28 02:25 UTC, cyz-2023 commented on include/sqlparser/sql_parse.y
> +        $$ = MYSQL_TYPE_LONG;
没有针对MYSQL_TYPE_BIT的逻辑，， 为了支持这个类型， 就用long去存储了

2024-11-28 02:48 UTC, cyz-2023 commented on src/exec/fetcher_store.cpp
> +            write_binlog_param.fetcher_store = this;
optype = rollback的时候， 会走到write_binlog里面，取param->client_conn时出core

2024-11-28 02:56 UTC, lgqss commented on include/sqlparser/sql_parse.y
> +        $$ = MYSQL_TYPE_LONG;
sql parser可以不变，可以ddl那里映射到long

2024-11-28 02:58 UTC, cyz-2023 commented on src/protocol/network_server.cpp
> +    old_status = SchemaFactory::get_instance()->get_instance_status(addr).status;
传过来的是旧的， 有个场景，  store A在一轮检测的最后一个实例检测，  1s超时会设置为faulty， 但在设置为faulty之前。 已经开始下一轮检测了， 第二轮开始的时候取的status，中间不会变更status，第二轮检测完后应该设置为dead， 但因为是第二轮检测刚开始的时候拿的status， 所以old_status还等于normal。

2024-11-28 03:23 UTC, cyz-2023 commented on src/expr/internal_functions.cpp
> +ExprValue json_extract1(const std::vector<ExprValue>& input) {
json对象的 ->和->>操作符返回的结果不一样， 就写了两个函数

2024-11-28 03:30 UTC, cyz-2023 commented on src/expr/expr_node.cpp
> +        int i = end_val.str_val.length() - 1;
这个是计算转成range之后的值的， 比如 a like '111%'，转成了 a >= 111 and a < '112'， 计算这个112的， 这段逻辑主要是为了防止最后一位+1后，需要进位，导致右边的值有问题

2024-11-28 03:40 UTC, cyz-2023 commented on src/expr/expr_node.cpp
> +    if (!is_prefix || old_val.length() > prefix_value.str_val.length() + 1) {
测试的时候发现的一种情况，  like 'aaa%bbb'这种不能转。

2024-11-29 08:30 UTC, lgqss commented on src/expr/expr_node.cpp
> +    if (!is_prefix || old_val.length() > prefix_value.str_val.length() + 1) {
为啥这种不能转来着，like的filter没删掉吧，还能过滤掉数据

2024-12-02 02:16 UTC, cyz-2023 commented on src/expr/expr_node.cpp
> +    if (!is_prefix || old_val.length() > prefix_value.str_val.length() + 1) {
这里转换之后，就把like去掉了， 加了个Range的， 如果不转换的话， 也是走之前逻辑。

2024-12-02 03:41 UTC, cyz-2023 commented on src/logical_plan/select_planner.cpp
> +    if (select_expr.nodes(0).node_type() != pb::AGG_EXPR) {
已修改

2024-12-02 03:41 UTC, cyz-2023 commented on src/common/expr_value.cpp
> +                oss << std::fixed << std::setprecision(float_precision_len);
已修改

2024-12-02 03:43 UTC, cyz-2023 commented on include/sqlparser/sql_parse.y
> +        $$ = MYSQL_TYPE_LONG;
已修改，ddl_planner中将bit映射为pb::int32

2024-12-02 06:58 UTC, lgqss requested changes

2024-12-02 06:59 UTC, lgqss requested changes

2024-12-02 06:59 UTC, lgqss commented on src/logical_plan/ddl_planner.cpp
> +        return pb::INT32;
不是INT64吗

2024-12-02 07:20 UTC, cyz-2023 commented on src/expr/internal_functions.cpp
> +ExprValue json_extract1(const std::vector<ExprValue>& input) {
是的， 就是带引号和不带引号两种都有， 那个json_extract不带引号

2024-12-02 07:25 UTC, cyz-2023 commented on src/expr/expr_node.cpp
> +        int i = end_val.str_val.length() - 1;
是的啊， 这个for 循环就是从后面找连续的255， 然后让前一位 + 1。 
end_val.str_val = end_val.str_val.substr(0, i + 1)

后面是这样赋值的，把最后的255去掉了。

2024-12-02 07:28 UTC, cyz-2023 commented on include/sqlparser/sql_parse.y
> +        $$ = MYSQL_TYPE_LONG;
搞错了， 修改为了int64

2024-12-02 07:30 UTC, cyz-2023 commented on src/logical_plan/ddl_planner.cpp
> +        return pb::INT32;
已修改，是应该int64， mysql最大支持到64位

2024-12-04 07:44 UTC, merged